### ISSUE TITLE
Branches and wiki Q

### ISSUE THREAD

**Issue by Basilisvirus** [CShark/stm32usb#1]
I would like to know why there are two branches, whats up with each.   
And you dont seem to have a wiki, while you mention of a wiki on your readme file.  
Thanks!

**Comment by CShark** [comment]
The wiki is here as part of the repo: https://github.com/CShark/stm32usb/wiki

You can ignore the usb_ncm branch, I should probably delete it. Originally I had planned on seperate branches for each USB function (CDC, NCM, HID,...) I was using, but decided to put everything in the main branch for easier maintainability. So the other branch is just a leftover from early decision making.
